services:
  php-8.4: &template
    build:
      context: ./docker/php
      args:
        PHP_VERSION: 8.4
    volumes:
      - ./:/app
    tty: true

  php-8.5:
    <<: *template
    build:
      context: ./docker/php
      args:
        PHP_VERSION: 8.5
